# General setup parameters
seed: 0 # run seed
channel_model: 'AWGN' # Physical channel models: ['AWGN']
decoder_type: 'bayesian_wbp' # 'bp','wbp','seq_wbp','bayesian_wbp','model_based_bayesian_wbp'
code_bits: 63
info_bits: 45
iterations: 5

# Training
train_snr_start: 4
train_snr_end: 7
train_block_size: 500 # coherence block time. values: int.
train_blocks_num: 10 # number of train frames. values: int.
loss_type: 'BCEWithLogits' # Loss type. values: 'BCEWithLogits','CrossEntropy','MSE'.
optimizer_type: 'Adam' # Optimizer type. values: 'Adam','RMSprop','SGD'.

# Validation
val_snr: 7 # validation SNR value. values: float.
val_block_size: 1000 # coherence block time. values: int.
val_blocks_num: 50 # number of validation frames. values: int.