# general
seed: 0 # run seed

# channel
channel_model: 'AWGN' # Physical channel models: ['AWGN']
decoder_type: 'wbp' # 'wbp','bp','seq_wbp','model_based_bayesian_wbp'
snr: 6 # validation SNR value. values: float.
code_bits: 63
info_bits: 36
iterations: 5

# protocol
block_length: 6000 # coherence block time, total size of pilot + data. values: int.
pilot_size: 2000 # pilot bits
blocks_num: 50 # number of validation frames. values: int.

# online training hyperparameters
loss_type: 'BCEWithLogits' # Loss type. values: 'BCEWithLogits','CrossEntropy','MSE'.
optimizer_type: 'Adam' # Optimizer type. values: 'Adam','RMSprop','SGD'.